const constants = {
  SIGNIN_REQUEST: 'SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'SIGNIN_SUCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGNOUT: 'SIGNOUT',
  AUTH: 'AUTH',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_ROLES_REQUEST: 'GET_ROLES_REQUEST',
  GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  ADD_USER_FAILURE: 'ADD_USER_FAILURE',
  ADD_USER_REQUEST: 'ADD_USER_REQUEST',
  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
};

export default constants;
